### ISSUE TITLE
postgres version

### ISSUE THREAD

**Issue by bbeesley** [giuseppeborgese/terraform-aws-secret-manager-with-rotation#1]
Hi, I forked your repo a few weeks ago because I needed to terraform secrets manager for an aurora Postgres cluster. My fork is here: https://github.com/bbeesley/terraform-aws-secret-manager-with-rotation
You don't seem to have a license on this project, so while I'd like to publish the Postgres version I can't really do that at the moment. Would you mind adding a license so I can publish? Or would you like to work together on modifying your version so it can work with Postgres as well as mysql (maybe not the best idea as we'd need two lambda code bundles)?
Let me know how you want to proceed with this, cheers.

**Comment by giuseppeborgese** [comment]
Hello Bill Beesley, you can do what you want with my project :) . If you tell me also which license is suitable I can add it to my project, I don't know well the license part. 
I have also added you on linkedin for short messages. 
Happy to be helpful

**Comment by bbeesley** [comment]
Hi, thanks for the quick response. I'd suggest MIT as an open license to allow people to use it as they please, but you can find more info on choosing a license and adding it to your repo here: https://choosealicense.com
I've accepted your linkedin but I'm afraid I don't use linkedin very much 😄

**Comment by giuseppeborgese** [comment]
I added a mit license file
