### ISSUE TITLE
more than one secret

### ISSUE THREAD

**Issue by ismferd** [giuseppeborgese/terraform-aws-secret-manager-with-rotation#4]
Do you have some tip to build more than one secret at time?

**Comment by giuseppeborgese** [comment]
Sorry, I forgot to answer you. Are you experimenting any issue to deploy more than one secret at the time?

**Comment by giuseppeborgese** [comment]
You can have multiple secrets and only 1 lambda, the only thing you need to pay attention to is that if you have multiple databases you need to be sure the lambda can access to all, so checks always the security group and routing (the same VPC I guess).

**Comment by ismferd** [comment]
Thanks for your answer @giuseppeborgese
